Repository microsoft/commercial-marketplace-offer-deploy, pull requests merged in 2023-05, with the labels that each got.

#215 feat: Adding retry to dry run
  build/package/Dockerfile.testharness
  cmd/apiserver/routes/routes.go
  cmd/operator/operations/base.go
  cmd/operator/operations/dryrun.go
  deployments/docker-compose.testharness.yml
  pkg/deployment/dryrun.go
  pkg/deployment/validators.go
  tools/test/deployment_test.go
  tools/testharness/app/app.go
Labels: enhancement

#220 feat: retry stage
  api/2023-03-01-preview/api.json
  cmd/apiserver/handlers/deployment_create.go
  cmd/operator/handlers/operations.go
  cmd/operator/operations/retryStage.go
  internal/data/models.go
  internal/mapper/createdeployment.go
  pkg/api/zz_generated_models.go
  pkg/api/zz_generated_models_serde.go
  pkg/deployment/azuredeployment.go
  pkg/deployment/deployment.go
  pkg/operations/model.go
  sdk/client_deployment.go
  sdk/model.go
  test/testdata/taggeddeployment/mainTemplateBicep.json
  tools/test/deployment_test.go
  tools/testharness/app/app.go
  tools/testharness/mainTemplateBicep.json
Labels: enhancement

#238 Bobjac/228
  cmd/operator/operations/dryrun.go
  go.work.sum
Labels: bug

#246 adding params check
  pkg/deployment/azuredeployment.go
  pkg/deployment/dryrun.go
  tools/test/deployment_test.go
Labels: enhancement

#261 254 - fixing topic name
  cmd/apiserver/eventgrid/subscriptionmanagement/manager.go
  cmd/apiserver/eventgrid/subscriptionmanagement/manager_test.go
Labels: bug

#265 Bug/259 param validations
  cmd/apiserver/handlers/deployment_invokeoperation_create.go
  go.mod
  go.sum
  internal/data/models_test.go
  pkg/deployment/dryrun.go
  pkg/deployment/validators.go
  test/deployment_test.go
  test/dryrun_test.go
  test/testdata/missingparam/mainTemplate.json
  test/testdata/missingparam/parameters.json
  test/testdata/taggeddeployment/mainTemplate.json
  test/testdata/taggeddeployment/parameters.json
Labels: bug

#269 v1 - Bobjac/template params
  pkg/deployment/azuredeployment.go
  pkg/deployment/azuredeployment_test.go
  pkg/deployment/dryrun.go
  pkg/deployment/validators.go
Labels: enhancement, v1

#268 v1 fix/267 - sanitized deployment name
  cmd/operator/operations/dryrun.go
  cmd/operator/operations/dryrun_test.go
  internal/data/models_extension.go
  internal/data/models_extension_test.go
Labels: bug, v1

#272 adding additional test to dry run, confirming the correct, fixing tests
  cmd/operator/operations/dryrun.go
  cmd/operator/operations/dryrun_test.go
  cmd/operator/operations/start.go
  cmd/operator/operations/start_test.go
  test/fakes/hookqueue.go
Labels: bug

#276 appending results
  cmd/operator/operations/base.go
  cmd/operator/operations/dryrun.go
  cmd/operator/operations/dryrun_test.go
  go.work.sum
  pkg/deployment/deployment.go
  pkg/deployment/dryrun.go
  pkg/deployment/validators.go
Labels: bug

#283 Bobjac/params mod
  pkg/deployment/azuredeployment.go
  pkg/deployment/dryrun.go
  test/dryrun_test.go
  test/testdata/directparamsmap/mainTemplate.json
  tools/go.mod
  tools/go.sum
Labels: bug

#291 Bobjac/log fix
  internal/log/log.go
Labels: bug, v1
